# Generated by Django 5.0.1 on 2024-01-15 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tiempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tiempo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última modificación')),
                ('tarea', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tiempo_asignado', to='proyectos.tarea')),
                ('usuario', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tiempo_asignado', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(default=1, help_text='Usuario de creación', on_delete=django.db.models.deletion.PROTECT, related_name='tiempo_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(default=1, help_text='Usuario de última modificación', on_delete=django.db.models.deletion.PROTECT, related_name='tiempo_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
