# Generated by Django 5.0.1 on 2024-01-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_tiempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='fechafin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fechaini',
            field=models.DateField(),
        ),
    ]
